# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - windows

julia:
  - 1.5
  - nightly

matrix:
  allow_failures:
  - julia: nightly
  
notifications:
  email: false
