# Documentation: http://docs.travis-ci.com/user/languages/julia/
coveralls: true
codecov: true
language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.1
  - 1.4
  - 1.5
  - nightly

matrix:
  allow_failures:
  - julia: nightly
  - julia: 1.0
  - julia: 1.1

notifications:
  email: false
